### ISSUE TITLE
why fetch_by_user_id generate 2 cache read command?

### ISSUE THREAD

**Issue by xuxiangyang** [Shopify/identity_cache#369] opened 2018-05-16 11:37 UTC
```ruby
class UserCard < ActiveRecordBase
  include IdentityCache
  cache_index :user_id, unique: true
end

UserCard.fetch_by_user_id("fake_user_id")
```

this codes will get this output

```
Cache read: IDC:6:attr:UserCard:id:user_id:4971600222228405331
[IdentityCache] (cache_backend) cache hit for IDC:6:attr:UserCard:id:user_id:4971600222228405331
Cache read: IDC:6:blob:UserCard:6763756255281408786:f29c0b3d-f2c7-48e9-a844-0be66d9751ce
[IdentityCache] (cache_backend) cache hit for IDC:6:blob:UserCard:6763756255281408786:f29c0b3d-f2c7-48e9-a844-0be66d9751ce
```

it means `fetch_by_user_id `generate two cache read，the first one is getting the `id `,  the second is getting the object

```
IdentityCache.cache.fetch("IDC:6:attr:UserCard:id:user_id:4971600222228405331")
Cache read: IDC:6:attr:UserCard:id:user_id:4971600222228405331
[IdentityCache] (cache_backend) cache hit for IDC:6:attr:UserCard:id:user_id:4971600222228405331
 => "f29c0b3d-f2c7-48e9-a844-0be66d9751ce"
```

```
IdentityCache.cache.fetch("IDC:6:blob:UserCard:6763756255281408786:f29c0b3d-f2c7-48e9-a844-0be66d9751ce")
Cache read: IDC:6:blob:UserCard:6763756255281408786:f29c0b3d-f2c7-48e9-a844-0be66d9751ce
[IdentityCache] (cache_backend) cache hit for IDC:6:blob:UserCard:6763756255281408786:f29c0b3d-f2c7-48e9-a844-0be66d9751ce
 => {:attributes=>{"id"=>"f29c0b3d-f2c7-48e9-a844-0be66d9751ce", "user_id"=>"008d7ac6-bfe2-4f20-942d-59fce58c76eb", "created_at"=>"2018-05-16 07:09:33.961385", "updated_at"=>"2018-05-16 07:09:33.961385"}, :class=>UserCard(id: uuid, user_id: uuid, created_at: datetime, updated_at: datetime)}
```

why? this plan will use less the memory ?

**Comment by dylanahsmith** [comment] 2018-05-16 14:34
Yes, it is working that way as intended.

I'm not sure of the initial reasons, but the extra round trip to the cache doesn't seem like a problem.  Our concern was more so with reducing load on the database for reads.

There are certainly trade-offs to normalization or denormalization.  As you said, it uses less memory.  Another advantage could be that it would expire less often, since it would only be expired when that column is modified rather than when any part of the row is modified.

On the other hand, we denormalize cache_has_one and cache_has_many associations and don't even support fully normalizing those associations (cache_has_many can only embed the ids).  I think that denormalization was a premature optimization and can easily result in over-fetching data.  It is also inconsistent with `cache_index`.

Is the current behaviour an actual problem for you?  Or should I close the issue?

**Comment by xuxiangyang** [comment] 2018-06-02 12:09
sorry for reply too late....

I think when call `UserCard.fetch_by_user_id` will generate too cache read command will produce twice qps  for cache store, which may lead to more load on the cache store machine.

The count of read may be 10 times lager than the count of updating in typical web server, I think it not worth to reduce the expire command.

I think the `cache_has_many` may not work well in the most cases in the bellow example

```
class User < ActiveRecord::Base
  has_may :posts
  cache_has_may :posts
end

class Post < ActiveRecord::Base
  belongs_to :user
  cache_belongs_to :user
end
```

a user may have many posts (for example 1000 posts), you can not use `u.fetch_posts` to load all posts from the cache for the size of data may be too large.

so, I think current behavior will lead to twice load to the cache machine, may be a better solution should balance the qps with memory usage. Just

**Closed** 2018-06-02 12:17 UTC
Labels: question
